export const EnemyType = Object.freeze({
  GRUNT: 'grunt',
  RUNNER: 'runner',
  BRUTE: 'brute',
  SABOTEUR: 'saboteur',
  SKIRMISHER: 'skirmisher',
  ARTILLERY: 'artillery',
  MOTHERSHIP: 'mothership',
})

export const ROLE_GROUPS = {
  CORE: (s) => s.isCore,
  INFRA: (s) => ['collector', 'battery', 'healer', 'relay'].includes(s.role),
  GENERATOR: (s) => s.role === 'collector',
  DEFENSE: (s) => ['turret', 'missile'].includes(s.role),
  NODE: (s) => s.role === 'relay',
}

export const REGISTRY = {
  [EnemyType.GRUNT]: {
    hp: 18, speed: 40, scale: 0.65, reward: 6,
    color: 0x49e07a, textureKey: 'enemy_grunt',
    targetPriority: 'DEFENSE',
    targetSecondary: 'CORE',
    movement: 'STRAIGHT',
    attack: 'LIGHT_LASER',
    attackRange: 120, atkCooldown: 700, damage: 4,
    beamColor: 0x49e07a,
    maxForce: 160,
    agility: 0.2,
    risk: 'BRAVE',
    evasion: 'JUKE',
    evasionChance: 0.35,
  },
  [EnemyType.RUNNER]: {
    hp: 12, speed: 78, scale: 0.6, reward: 5,
    color: 0xffd24a, textureKey: 'enemy_runner',
    targetPriority: 'CORE',
    targetSecondary: 'DEFENSE',
    movement: 'WEAVE',
    attack: 'MELEE',
    attackRange: 0, atkCooldown: 500, damage: 4,
    maxForce: 360,
    agility: 0.35,
    evasion: 'SERPENTINE',
    risk: 'CAUTIOUS',
    evasionChance: 0.90,
  },
  [EnemyType.BRUTE]: {
    hp: 80, speed: 24, scale: 1.0, reward: 22,
    color: 0xff5566, textureKey: 'enemy_brute',
    targetPriority: 'DEFENSE',
    targetSecondary: 'CORE',
    movement: 'STRAIGHT',
    attack: 'LIGHT_LASER',
    attackRange: 160, atkCooldown: 900, damage: 9,
    beamColor: 0xff5566,
    maxForce: 120,
    agility: 0.1,
    risk: 'BRAVE',
    evasion: 'JUKE',
    evasionChance: 0.10,
  },
  [EnemyType.SABOTEUR]: {
    hp: 60, speed: 30, scale: 0.8, reward: 18,
    color: 0xff5566, textureKey: 'enemy_saboteur',
    targetPriority: 'GENERATOR',
    targetSecondary: 'NODE',
    movement: 'APPROACH_THEN_HOLD',
    attack: 'BEAM',
    attackRange: 130, atkCooldown: 1200, damage: 14,
    beamColor: 0xff5566, beamWidth: 3,
    maxForce: 200,
    agility: 0.2,
    evasion: 'JUKE',
    risk: 'CALCULATED',
    evasionChance: 0.50,
  },
  [EnemyType.SKIRMISHER]: {
    hp: 35, speed: 50, scale: 0.75, reward: 16,
    color: 0x49e07a, textureKey: 'enemy_skirmisher',
    targetPriority: 'GENERATOR',
    targetSecondary: 'DEFENSE',
    movement: 'KEEP_DISTANCE',
    attack: 'MISSILE',
    attackRange: 200, atkCooldown: 1800, damage: 12,
    splash: 40, projSpeed: 160,
    maxForce: 320,
    agility: 0.3,
    evasion: 'STRAFE_BURST',
    risk: 'CAUTIOUS',
    evasionChance: 0.80,
  },
  [EnemyType.ARTILLERY]: {
    hp: 40, speed: 18, scale: 0.85, reward: 30,
    color: 0xffd24a, textureKey: 'enemy_artillery',
    targetPriority: 'NODE',
    targetSecondary: 'CORE',
    movement: 'STANDOFF',
    attack: 'MISSILE',
    attackRange: 500, atkCooldown: 2200, damage: 20,
    splash: 50, projSpeed: 140,
    preferredRange: 600,
    maxForce: 150,
    agility: 0.12,
    evasion: 'JUKE',
    risk: 'CALCULATED',
    evasionChance: 0.45,
  },
  [EnemyType.MOTHERSHIP]: {
    hp: 440, speed: 18, scale: 1.7, reward: 160,
    color: 0xc08bff, textureKey: 'enemy_mothership',
    targetPriority: 'CORE',
    targetSecondary: 'DEFENSE',
    movement: 'STRAIGHT',
    attack: 'BIG_BEAM',
    attackRange: 220, atkCooldown: 2000, damage: 35,
    beamColor: 0xc08bff, beamWidth: 8,
    boss: true,
    maxForce: 90,
    agility: 0.05,
    risk: 'BRAVE',
    evasion: 'JUKE',
    evasionChance: 0.05,
  },
}
