export const EnemyType = Object.freeze({
  GRUNT: 'grunt',
  RUNNER: 'runner',
  BRUTE: 'brute',
  SABOTEUR: 'saboteur',
  SKIRMISHER: 'skirmisher',
  ARTILLERY: 'artillery',
  MOTHERSHIP: 'mothership',
  COMMANDSHIP: 'commandship',
  KAMIKAZE: 'kamikaze',
  WARDEN: 'warden',
  LEECH: 'leech',
  BOMBER: 'bomber',
})

export const ROLE_GROUPS = {
  CORE: (s) => s.isCore,
  INFRA: (s) => ['collector', 'battery', 'healer', 'relay'].includes(s.role),
  GENERATOR: (s) => s.role === 'collector',
  SUPPLY: (s) => ['collector', 'battery'].includes(s.role),
  DEFENSE: (s) => ['turret', 'missile'].includes(s.role),
  NODE: (s) => s.role === 'relay',
}

export const REGISTRY = {
  [EnemyType.GRUNT]: {
    hp: 18, speed: 40, scale: 0.65, reward: 6,
    color: 0x49e07a, textureKey: 'enemy_grunt',
    targetPriority: 'DEFENSE',
    targetSecondary: 'CORE',
    movement: 'STRAIGHT',
    attack: 'LIGHT_LASER',
    attackRange: 120, atkCooldown: 700, damage: 4,
    beamColor: 0x49e07a,
    maxForce: 160,
    agility: 0.2,
    risk: 'BRAVE',
    evasion: 'JUKE',
    evasionChance: 0.35,
  },
  [EnemyType.RUNNER]: {
    hp: 12, speed: 78, scale: 0.6, reward: 5,
    color: 0x38e0d0, textureKey: 'enemy_runner',
    targetPriority: 'CORE',
    targetSecondary: 'DEFENSE',
    movement: 'WEAVE',
    attack: 'MELEE',
    attackRange: 0, atkCooldown: 500, damage: 4,
    maxForce: 360,
    agility: 0.35,
    evasion: 'SERPENTINE',
    risk: 'CAUTIOUS',
    evasionChance: 0.90,
  },
  [EnemyType.BRUTE]: {
    // Velocidad al nivel de la horda (grunt=40) para que no se queden atrás.
    hp: 80, speed: 42, scale: 1.0, reward: 22,
    color: 0xff6b3d, textureKey: 'enemy_brute',
    targetPriority: 'DEFENSE',
    targetSecondary: 'CORE',
    movement: 'STRAIGHT',
    attack: 'LIGHT_LASER',
    attackRange: 160, atkCooldown: 900, damage: 9,
    beamColor: 0xff6b3d,
    maxForce: 200,
    agility: 0.1,
    risk: 'BRAVE',
    evasion: 'JUKE',
    evasionChance: 0.10,
  },
  [EnemyType.SABOTEUR]: {
    hp: 60, speed: 44, scale: 0.8, reward: 20,
    color: 0xd24aff, textureKey: 'enemy_saboteur',
    targetPriority: 'SUPPLY',
    targetSecondary: 'INFRA',
    movement: 'KEEP_DISTANCE',
    attack: 'MISSILE',
    attackRange: 260, atkCooldown: 1800, damage: 12,
    splash: 40, projSpeed: 160,
    maxForce: 320,
    agility: 0.3,
    evasion: 'STRAFE_BURST',
    risk: 'CAUTIOUS',
    evasionChance: 0.80,
  },
  [EnemyType.SKIRMISHER]: {
    hp: 35, speed: 50, scale: 0.75, reward: 20,
    color: 0xa6e022, textureKey: 'enemy_skirmisher',
    targetPriority: 'INFRA',
    targetSecondary: 'DEFENSE',
    movement: 'KEEP_DISTANCE',
    attack: 'MISSILE',
    attackRange: 260, atkCooldown: 1800, damage: 12,
    splash: 40, projSpeed: 160,
    maxForce: 320,
    agility: 0.3,
    evasion: 'STRAFE_BURST',
    risk: 'CAUTIOUS',
    evasionChance: 0.80,
  },
  [EnemyType.ARTILLERY]: {
    hp: 40, speed: 18, scale: 0.85, reward: 30,
    color: 0xffb02e, textureKey: 'enemy_artillery',
    targetPriority: 'NODE',
    targetSecondary: 'CORE',
    movement: 'STANDOFF',
    attack: 'MISSILE',
    attackRange: 500, atkCooldown: 2200, damage: 20,
    splash: 50, projSpeed: 140,
    preferredRange: 600,
    maxForce: 150,
    agility: 0.12,
    evasion: 'JUKE',
    risk: 'CALCULATED',
    evasionChance: 0.45,
  },
  // Nave Madre: portanaves naranja. Va hacia el Nexo, se mantiene a distancia y
  // hereda la habilidad de spawnear naves pequeñas. Más rápida para acompañar la horda.
  [EnemyType.MOTHERSHIP]: {
    hp: 1000, speed: 36, scale: 3.4, reward: 350,
    color: 0xff8a3d, textureKey: 'enemy_mothership',
    targetPriority: 'CORE',
    targetSecondary: 'DEFENSE',
    movement: 'STANDOFF',
    preferredRange: 420,
    attack: 'SPAWN_SMALL_SHIPS',
    attackRange: 0, atkCooldown: 8000, damage: 0,
    spawnCount: 3,
    spawnTypes: ['grunt', 'runner'],
    spawnInterval: 8000,
    boss: true,
    maxForce: 160,
    agility: 0.08,
    risk: 'BRAVE',
    evasion: 'JUKE',
    evasionChance: 0.05,
  },
  // Nave Nodriza: jefe único de la partida. Vida masiva, múltiples láseres que
  // atacan objetivos independientes, misil EMP periódico que paraliza estructuras.
  // Velocidad y maxForce subidos: a 22px/s tardaba 4+ min en cruzar el mapa desde el
  // borde de spawn hasta el núcleo y quedaba "perdida" entre los ~300 enemigos de la
  // oleada — parecía que nunca aparecía.
  [EnemyType.COMMANDSHIP]: {
    hp: 12000, speed: 60, scale: 5.5, reward: 1200,
    color: 0xb06bff, textureKey: 'enemy_commandship',
    targetPriority: 'CORE',
    targetSecondary: 'DEFENSE',
    movement: 'STRAIGHT',
    attack: 'BOSS_MULTI_LASER',
    attackRange: 460, atkCooldown: 1500, damage: 14,
    beamColor: 0xd24aff, beamWidth: 5,
    laserCount: 4,          // láseres simultáneos, cada uno con su propio objetivo
    empInterval: 1800000,   // 30 min entre misiles EMP
    empStunMs: 8000,        // parálisis de estructuras al impactar
    empRadius: 300,
    empSpeed: 120,
    boss: true,
    maxForce: 240,
    agility: 0.08,
    risk: 'BRAVE',
    evasion: 'JUKE',
    evasionChance: 0.05,
  },
  // ---- Fase 10: enemigos por sector (meta/sectors.js los habilita) ----
  // Kamikaze: rápido y frágil; detona contra las defensas.
  [EnemyType.KAMIKAZE]: {
    hp: 16, speed: 96, scale: 0.7, reward: 8,
    color: 0xff4d2e, textureKey: 'enemy_kamikaze',
    targetPriority: 'DEFENSE',
    targetSecondary: 'CORE',
    movement: 'STRAIGHT',
    attack: 'KAMIKAZE',
    attackRange: 0, atkCooldown: 0, damage: 28, splash: 55,
    maxForce: 420,
    agility: 0.4,
    risk: 'BRAVE',
    evasion: 'SERPENTINE',
    evasionChance: 0.5,
  },
  // Warden: tanque que repara a la horda a su alrededor. Prioridad para el Mega Rayo.
  [EnemyType.WARDEN]: {
    hp: 220, speed: 30, scale: 1.25, reward: 45,
    color: 0x7fb2ff, textureKey: 'enemy_warden',
    targetPriority: 'DEFENSE',
    targetSecondary: 'CORE',
    movement: 'STRAIGHT',
    attack: 'SHIELD_AURA',
    attackRange: 150, atkCooldown: 1100, damage: 7,
    beamColor: 0x7fb2ff,
    auraRadius: 150, auraHeal: 0.05, auraInterval: 1000,
    maxForce: 160,
    agility: 0.08,
    risk: 'BRAVE',
    evasion: 'JUKE',
    evasionChance: 0.05,
  },
  // Leech: parásito que va a los recolectores y drena energía de la red.
  [EnemyType.LEECH]: {
    hp: 40, speed: 62, scale: 0.8, reward: 18,
    color: 0xff3dbd, textureKey: 'enemy_leech',
    targetPriority: 'GENERATOR',
    targetSecondary: 'SUPPLY',
    movement: 'WEAVE',
    attack: 'DRAIN',
    attackRange: 0, atkCooldown: 700, damage: 5, drain: 8,
    maxForce: 340,
    agility: 0.3,
    risk: 'CAUTIOUS',
    evasion: 'SERPENTINE',
    evasionChance: 0.7,
  },
  // Bomber: artillería pesada con mucha área; castiga las defensas agrupadas.
  [EnemyType.BOMBER]: {
    hp: 110, speed: 26, scale: 1.2, reward: 40,
    color: 0xffb02e, textureKey: 'enemy_bomber',
    targetPriority: 'DEFENSE',
    targetSecondary: 'INFRA',
    movement: 'STANDOFF',
    attack: 'MISSILE',
    attackRange: 420, atkCooldown: 3000, damage: 26,
    splash: 90, projSpeed: 120,
    preferredRange: 380,
    maxForce: 150,
    agility: 0.1,
    risk: 'CALCULATED',
    evasion: 'JUKE',
    evasionChance: 0.2,
  },
}
